# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.srcs/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0.xci
# IP: The module: 'processing_system_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.srcs/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0.xci
# IP: The module: 'processing_system_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
