# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/Src/vc707_fmc216_vivado.xdc

# Block Designs: bd/processing_system/processing_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system || ORIG_REF_NAME==processing_system} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_processing_system7_0_0/processing_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_processing_system7_0_0 || ORIG_REF_NAME==processing_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_axi_gpio_0_0/processing_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_axi_gpio_0_0 || ORIG_REF_NAME==processing_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_xbar_0/processing_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_xbar_0 || ORIG_REF_NAME==processing_system_xbar_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_auto_pc_0/processing_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_auto_pc_0 || ORIG_REF_NAME==processing_system_auto_pc_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_ps7_0_axi_periph_0/processing_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==processing_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_rst_ps7_0_50M_0/processing_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==processing_system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_clk_wiz_0_0/processing_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_clk_wiz_0_0 || ORIG_REF_NAME==processing_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_axi_gpio_1_0/processing_system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_axi_gpio_1_0 || ORIG_REF_NAME==processing_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/processing_system/ip/processing_system_AXI_ZC706_FMC216_0_2/processing_system_AXI_ZC706_FMC216_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_system_AXI_ZC706_FMC216_0_2 || ORIG_REF_NAME==processing_system_AXI_ZC706_FMC216_0_2} -quiet] -quiet

# IP: ip/xcvr_fmc216/xcvr_fmc216.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xcvr_fmc216 || ORIG_REF_NAME==xcvr_fmc216} -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/bd/processing_system/processing_system_ooc.xdc
