# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216.xci
# IP: The module: 'xcvr_fmc216' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcvr_fmc216'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcvr_fmc216'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216.xci
# IP: The module: 'xcvr_fmc216' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcvr_fmc216'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/527_vc707_fmc216/output/vc707_fmc216_vivado/Src/sip_fmc216_8lane/xcvr_fmc216/xcvr_fmc216_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcvr_fmc216'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
