# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.srcs/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo.xci
# IP: The module: 'dac3283_wfm_output_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.srcs/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo.xci
# IP: The module: 'dac3283_wfm_output_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/4dsp_test/zc706_fmc216/output/vc707_fmc216_vivado/vivado/vc707_fmc216_vivado.gen/sources_1/ip/dac3283_wfm_output_fifo/dac3283_wfm_output_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac3283_wfm_output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
